checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    nodes:
        analysis:
            environment:
                php: 7.4.12

            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            environment:
                php: 7.4.12

            dependencies:
                override:
                    - composer self-update
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
                    - vendor/bin/yii --config=tests migrate/up --no-interaction

            tests:
                override:
                    -
                        command: |
                            php -S 127.0.0.1:8080 -t tests/_data/public > ./runtime/yii.log 2>&1 &
                            vendor/bin/codecept run --coverage-xml
                        on_node: 1
                        coverage:
                            file: tests/_output/coverage.xml
                            format: php-clover


