checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    nodes:
        analysis:
            environment:
                php: 7.4.12

            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            environment:
                php: 7.4.12

            dependencies:
                override:
                    - composer self-update
                    - composer create-project --prefer-dist --no-interaction --no-progress --stability=dev yii-extension/app-bulma demo-bulma --ansi
                    - cd demo-bulma
                    - composer require yii-extension/user yii-extension/user-view-bulma --ansi
                    - Alternatives='tests' ./yii migrate/up --no-interaction

            tests:
                override:
                    -
                        command: |
                            php -S 127.0.0.1:8080 -t public public/index-test.php > ./runtime/yii.log 2>&1 &
                            vendor/bin/codecept run -c vendor/yii-extension/user --coverage-xml
                        on_node: 1
                        coverage:
                            file: vendor/yii-extension/user/tests/_output/coverage.xml
                            format: php-clover


