checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    nodes:
        analysis:
            environment:
                php: 7.4.12

            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            environment:
                php: 7.4.12

            dependencies:
                override:
                    - composer self-update
                    - composer require yii-extension/user-view-bulma:@dev --dev --ansi

            tests:
                override:
                    -
                        command: |
                            composer du
                            php -S 127.0.0.1:8080 -t tests/_data/public > tests/_data/runtime/yii.log 2>&1 &
                            vendor/bin/codecept run Unit,Acceptance,Functional --coverage-html
                        on_node: 1
                        coverage:
                            file: tests/_output/coverage.xml
                            format: php-clover


